drop table if exists city;

create table city (
  id int primary key generated by default as identity,
  name varchar not null,
  state varchar,
  country varchar
);

insert into city (name, state, country) values ('San Francisco', 'CA', 'US');

commit;